#nfs-pv.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-vol
  annotations:
    pv.beta.kubernetes.io/gid: "1234"
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs.tp.lan # replace with your nfs server IP or hostname
    path: "/mnt/nfsvol" # replace with your mount path
